
kind: pipeline
type: docker
name: default

metadata:
  # shared image configuration for all python steps
  base_image: &base
    image: python:3.8
    volumes:
      - name: venv
        path: /venv

steps:
  - name: prepare
    <<: *base
    commands:
      - python3 -m venv /venv
      - /venv/bin/pip install -U wheel pip poetry
      - /venv/bin/poetry config virtualenvs.create false
      - /venv/bin/poetry install

  - name: test
    <<: *base
    commands:
      # run the tests
      - /venv/bin/pytest --cov=weevils/
      # needed because newer versions of git moan about the checkout ownership
      - git config --global --add safe.directory /drone/src
    depends_on:
      - prepare

  - name: lint
    <<: *base
    commands:
      # ensure that the pre-commit steps were run
      - /venv/bin/pre-commit run --all
    depends_on:
      - test

  - name: upload
    <<: *base
    environment:
      UPLOAD_KEY:
        from_secret: pypi-push
    commands:
      - echo "${UPLOAD_KEY}" > key && chown 0600 key
      - rm -rf dist/ && poetry build
      - sed -i "s/version = \"\(.*\)\"/version = \"\1-$(date +%Y%m%d%H%M)\"/" pyproject.toml
      - ssh -i key pypi@pypi.zerfeciz.com mkdir -p packages/weevils-python/
      - scp -i key pypi@pypi.zerfeciz.com:packages/weevils-python/
    depends_on:
      - lint
    when:
      branch:
        - master

volumes:
  - name: venv
    temp: {}
