
kind: pipeline
type: docker
name: default

metadata:
  # shared image configuration for all python steps
  base_image: &base
    image: python:3.8
    volumes:
      - name: venv
        path: /venv

steps:
  - name: prepare
    <<: *base
    commands:
      - python3 -m venv /venv
      - /venv/bin/pip install -U wheel pip poetry
      - /venv/bin/poetry config virtualenvs.create false
      - /venv/bin/poetry install

  - name: test
    <<: *base
    commands:
      # run the tests
      - /venv/bin/pytest --cov=weevils/
    depends_on:
      - prepare

  - name: lint
    <<: *base
    commands:
      # needed because newer versions of git moan about the checkout ownership
      - git config --global --add safe.directory /drone/src
      # ensure that the pre-commit steps were run
      - /venv/bin/pre-commit run --all
    depends_on:
      - test

  - name: upload
    <<: *base
    environment:
      UPLOAD_KEY:
        from_secret: pypi-push
    commands:
      - /bin/bash upload.sh
    depends_on:
      - lint
    when:
      branch:
        - master

volumes:
  - name: venv
    temp: {}
